name: 'GitHub Action Test'

on:
  push:
    branches:
      - main
    tags:
      - release.*

jobs:
  Job-Test:
    #컨테이너를 지정
    runs-on: ubuntu-latest
    steps:
      - run: echo "...${{github.repository}}"
